### ISSUE TITLE
How do I use these snippets?

### ISSUE THREAD

**Issue by csakis** [JonathanBergson/atom-jade-snippets#1]
I tried [TAB] [Ctrl]-[Space]. They don't seem to work.

**Comment by JonathanBergson** [comment]
The snippets are functioning normally.
Start typing a snippet and press [Tab].

My Atom version: 1.2.1
I use the syntax plugin: https://atom.io/packages/atom-jade

**Comment by csakis** [comment]
I have the same packages and pushing TAB does not do anything. Weird.

**Comment by JonathanBergson** [comment]
I do not know what might be happening :[

**Comment by vingorius** [comment]
After install, this module does not work, but after **restart** atom, it works.

**Comment by JonathanBergson** [comment]
You installed using command line?

**Comment by vingorius** [comment]
No, thru atom menu.
